apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: web
  template: 
    metadata:
      labels:
        app: web 
    spec:
      containers:
      - name: web 
        image: httpd:2.4-alpine
        ports:
          - containerPort: 80
        volumeMounts:
          - name: apache-config-volume 
            mountPath: /usr/local/apache2/conf
          - name: mime-config-volume 
            mountPath: /etc/mime.types
      volumes:
        - name: apache-config-volume
          configMap:
            name: httpd-config
            items:
              - key: httpd.conf 
                path: httpd.conf
        - name: mime-config-volume
          configMap:
            name: mime-config
            items:
              - key: mime.types
                path: mime.types
---
apiVersion: v1 
kind: Service 
metadata:
  name: web-service 
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
      nodePort: 30000