services:
  web:
    build: nginx
    restart: always
    ports:
     - 80:80
    depends_on:
      - backend
    networks:
      - frontnet

  backend:
    build:
      context: src
    restart: always
    networks:
      - frontnet
      - backnet
    depends_on:
      - db
  
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - backnet
  
volumes:
  mongodb_data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet: