global:
  scrape_interval: 15s  
  evaluation_interval: 15s  

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  

  - job_name: 'webapp'
    static_configs:
      - targets: ['nginx-exporter:9113']  
  
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']  
  
  - job_name: 'node-exp'
    static_configs:
      - targets: ['node-exporter:9100']  

  

rule_files:
  - 'alert.rules.yml'  
